## DT on House Prices dataset

In [70]:
import pandas as pd
import numpy as np
%matplotlib inline
import sklearn.model_selection as cv
import sklearn         
import matplotlib.pyplot as plt

In [71]:
## Load datasets
train_data = pd.read_csv('../datasets/preprocessed/train.csv', sep=',')
test_data = pd.read_csv('../datasets/preprocessed/test.csv', sep=',')

print('Train data size ' + str(train_data.shape))
print('Test data size ' + str(test_data.shape))

train_data.head() 
test_data.head() 

Train data size (1006, 47)
Test data size (432, 47)


MSSubClass MSZoning   LotArea  LotShape LandContour LotConfig Neighborhood  \
0          L       RL  0.476744       0.0         Lvl    Inside      Veenker   
1          E       RM  0.156670       1.0         Lvl    Corner      OldTown   
2          F       RL  0.349489       1.0         Lvl    Corner       Timber   
3          F       RL  0.336509       0.0         Lvl    Inside      NoRidge   
4          F       RL  0.280435       0.0         Lvl    Inside      CollgCr   

  Condition1 BldgType HouseStyle  ...  Fence  MiscVal SaleType SaleCondition  \
0       Norm    Twnhs     1Story  ...    0.0      0.0       WD        Normal   
1       Norm     1Fam     2Story  ...    0.0      0.0       WD        Normal   
2       Norm     1Fam     2Story  ...    0.0      0.0       WD        Normal   
3       Norm     1Fam     2Story  ...    0.0      0.0       WD        Normal   
4       Norm     1Fam     2Story  ...    0.0      0.0       WD        Normal   

  SalePrice  MasVnr SecondFloor Baths Porch Pool  
0    Level3     0.0         0.0   0.4  True  0.0  
1    Level2     0.0         1.0   0.2  True  0.0  
2    Level3     1.0         1.0   0.6  True  0.0  
3    Level3     1.0         1.0   0.6  True  0.0  
4    Level3     0.0         1.0   0.6  True  0.0  

[5 rows x 47 columns]

In [72]:
## Separate data from labels
y_train = train_data['SalePrice']
y_test = test_data['SalePrice']

x_train = train_data.select_dtypes(include=['bool','object']) ## select categorical data FALTAN!!!
x_train = x_train.drop(['SalePrice'], axis=1)

x_test = test_data.select_dtypes(include=['bool','object']) ## select categorical data FALTAN!!!
x_test = x_test.drop(['SalePrice'], axis=1)

print('x_train size ' + str(x_train.shape))
print('x_test size ' + str(x_test.shape))

x_train.head()
x_test.head()

x_train size (1006, 25)
x_test size (432, 25)


MSSubClass MSZoning LandContour LotConfig Neighborhood Condition1 BldgType  \
0          L       RL         Lvl    Inside      Veenker       Norm    Twnhs   
1          E       RM         Lvl    Corner      OldTown       Norm     1Fam   
2          F       RL         Lvl    Corner       Timber       Norm     1Fam   
3          F       RL         Lvl    Inside      NoRidge       Norm     1Fam   
4          F       RL         Lvl    Inside      CollgCr       Norm     1Fam   

  HouseStyle RoofStyle RoofMatl  ... Functional  FireplaceQu GarageType  \
0     1Story     Gable  CompShg  ...        Typ           Gd     Attchd   
1     2Story   Gambrel  CompShg  ...        Typ  NoFireplace     Detchd   
2     2Story     Gable  CompShg  ...        Typ           Gd    BuiltIn   
3     2Story     Gable  CompShg  ...        Typ           TA     Attchd   
4     2Story     Gable  CompShg  ...        Typ  NoFireplace     Attchd   

  GarageFinish GarageQual GarageCond PavedDrive SaleType SaleCondition Porch  
0          Fin         TA         TA          Y       WD        Normal  True  
1          Unf         TA         TA          Y       WD        Normal  True  
2          Fin         TA         TA          Y       WD        Normal  True  
3          RFn         TA         TA          Y       WD        Normal  True  
4          RFn         TA         TA          Y       WD        Normal  True  

[5 rows x 25 columns]

In [73]:
## Prepare join dataset 
X = pd.concat([x_train, x_test])
print('Join X data size ' + str(X.shape))
X.head() 

Join X data size (1438, 25)


MSSubClass MSZoning LandContour LotConfig Neighborhood Condition1 BldgType  \
0          J       RL         Lvl   CulDSac      Mitchel       Norm     1Fam   
1          E       RL         Lvl    Inside        NAmes       Norm     1Fam   
2          J       RL         Lvl    Corner      Edwards       Norm     1Fam   
3          A       RL         Lvl    Corner        NAmes       Norm     1Fam   
4          F       RL         Lvl    Inside      NoRidge       Norm     1Fam   

  HouseStyle RoofStyle RoofMatl  ... Functional  FireplaceQu GarageType  \
0     SFoyer     Gable  CompShg  ...        Typ           TA     Attchd   
1     1.5Fin     Gable  CompShg  ...        Typ  NoFireplace   NoGarage   
2     SFoyer     Gable  CompShg  ...        Typ           Ex    BuiltIn   
3     1Story     Gable  CompShg  ...        Typ           Fa     Attchd   
4     2Story     Gable  CompShg  ...        Typ           TA     Attchd   

  GarageFinish GarageQual GarageCond PavedDrive SaleType SaleCondition  Porch  
0          RFn         TA         TA          Y       WD        Normal   True  
1     NoGarage   NoGarage   NoGarage          Y       WD       Abnorml  False  
2          RFn         TA         TA          Y    ConLD        Normal   True  
3          RFn         TA         TA          Y       WD        Normal   True  
4          Fin         TA         TA          Y       WD        Normal   True  

[5 rows x 25 columns]

In [74]:
## Transform to numerical dataset
Xn = pd.get_dummies(X)
print('Join Xn data size ' + str(Xn.shape))
Xn.head()

Join Xn data size (1438, 172)


Porch  MSSubClass_A  MSSubClass_B  MSSubClass_C  MSSubClass_D  \
0   True             0             0             0             0   
1  False             0             0             0             0   
2   True             0             0             0             0   
3   True             1             0             0             0   
4   True             0             0             0             0   

   MSSubClass_E  MSSubClass_F  MSSubClass_G  MSSubClass_H  MSSubClass_I  ...  \
0             0             0             0             0             0  ...   
1             1             0             0             0             0  ...   
2             0             0             0             0             0  ...   
3             0             0             0             0             0  ...   
4             0             1             0             0             0  ...   

   SaleType_ConLw  SaleType_New  SaleType_Oth  SaleType_WD  \
0               0             0             0            1   
1               0             0             0            1   
2               0             0             0            0   
3               0             0             0            1   
4               0             0             0            1   

   SaleCondition_Abnorml  SaleCondition_AdjLand  SaleCondition_Alloca  \
0                      0                      0                     0   
1                      1                      0                     0   
2                      0                      0                     0   
3                      0                      0                     0   
4                      0                      0                     0   

   SaleCondition_Family  SaleCondition_Normal  SaleCondition_Partial  
0                     0                     1                      0  
1                     0                     0                      0  
2                     0                     1                      0  
3                     0                     1                      0  
4                     0                     1                      0  

[5 rows x 172 columns]

In [75]:
## Split join dataset into training and test
X_train = Xn[0:1006]
X_test = Xn[1006:1438]

print('X_train size ' + str(X_train.shape))
print('X_test size ' + str(X_test.shape))

X_train.head()
X_test.head()

X_train size (1006, 172)
X_test size (432, 172)


Porch  MSSubClass_A  MSSubClass_B  MSSubClass_C  MSSubClass_D  \
0   True             0             0             0             0   
1   True             0             0             0             0   
2   True             0             0             0             0   
3   True             0             0             0             0   
4   True             0             0             0             0   

   MSSubClass_E  MSSubClass_F  MSSubClass_G  MSSubClass_H  MSSubClass_I  ...  \
0             0             0             0             0             0  ...   
1             1             0             0             0             0  ...   
2             0             1             0             0             0  ...   
3             0             1             0             0             0  ...   
4             0             1             0             0             0  ...   

   SaleType_ConLw  SaleType_New  SaleType_Oth  SaleType_WD  \
0               0             0             0            1   
1               0             0             0            1   
2               0             0             0            1   
3               0             0             0            1   
4               0             0             0            1   

   SaleCondition_Abnorml  SaleCondition_AdjLand  SaleCondition_Alloca  \
0                      0                      0                     0   
1                      0                      0                     0   
2                      0                      0                     0   
3                      0                      0                     0   
4                      0                      0                     0   

   SaleCondition_Family  SaleCondition_Normal  SaleCondition_Partial  
0                     0                     1                      0  
1                     0                     1                      0  
2                     0                     1                      0  
3                     0                     1                      0  
4                     0                     1                      0  

[5 rows x 172 columns]

In [76]:
## Train and Print A Decision Tree without Customize

from sklearn import tree
from statsmodels.stats.proportion import proportion_confint

clf = tree.DecisionTreeClassifier(criterion='entropy')
pred = clf.fit(X_train, y_train).predict(X_test)
print(sklearn.metrics.confusion_matrix(y_test, pred))
print()
print("Accuracy on test set:", sklearn.metrics.accuracy_score(y_test, pred))
print()
print(sklearn.metrics.classification_report(y_test, pred))
epsilon = sklearn.metrics.accuracy_score(y_test, pred)
print("Confidence interval: ",proportion_confint(count=epsilon*X_test.shape[0], nobs=X_test.shape[0], alpha=0.05, method='binom_test'))

# Print tree
fig = plt.gcf()
fig.set_size_inches(200, 100)

tree.plot_tree(clf, filled=True,rounded=True,feature_names=list(Xn.columns.values))
fig.savefig('tree.png')
plt.show()

[[ 14  18   1   0   0]
 [ 14 221  28   8   0]
 [  1  37  48  15   0]
 [  0   5   2  10   3]
 [  0   0   0   5   2]]

Accuracy on test set: 0.6828703703703703

              precision    recall  f1-score   support

      Level1       0.48      0.42      0.45        33
      Level2       0.79      0.82      0.80       271
      Level3       0.61      0.48      0.53       101
      Level4       0.26      0.50      0.34        20
      Level5       0.40      0.29      0.33         7

    accuracy                           0.68       432
   macro avg       0.51      0.50      0.49       432
weighted avg       0.69      0.68      0.68       432

Confidence interval:  (0.6366796957802529, 0.7258654036936276)


In [77]:
# Cross-validation of the first model 
scores = sklearn.model_selection.cross_val_score(clf, Xn, Y, cv=10)
print("Accuracy on 10 fold cross-validation:", scores)
print(np.mean(scores))

NameError: name 'Y' is not defined

In [ ]:
## Train and Print A Decision Tree ()

clf=tree.DecisionTreeClassifier(criterion='entropy', min_samples_split=2,min_impurity_decrease=0.02)
clf = clf.fit(X_train, y_train)
pred = clf.predict(X_test)

# Obtain accuracy score of learned classifier on test data
print(clf.score(X_test, y_test))
print(sklearn.metrics.confusion_matrix(y_test, pred))
print()
print("Accuracy:", sklearn.metrics.accuracy_score(y_test, pred))
print()
print(sklearn.metrics.classification_report(y_test, pred))
epsilon = sklearn.metrics.accuracy_score(y_test, pred)
print("Interval of confidence:", proportion_confint(count=epsilon*X_test.shape[0], nobs=X_test.shape[0], alpha=0.05, method='binom_test'))

# Print tree
fig = plt.gcf()
fig.set_size_inches(800, 80)

tree.plot_tree(clf, filled=True,rounded=True)
fig.savefig('tree.png')
plt.show()

In [ ]:
# Cross-validation of the previous model 
scores = sklearn.model_selection.cross_val_score(clf, Xn, Y, cv=10)
print("Accuracy on 10 fold cross-validation:", scores)
print(np.mean(scores))

In [ ]:
# Search of the best params
from sklearn.model_selection import GridSearchCV

params = {'min_impurity_decrease': list(np.linspace(0,0.5,21)),'min_samples_split':list(range(2,20,11))}
clf = GridSearchCV(tree.DecisionTreeClassifier(criterion='entropy'), param_grid=params,cv=10,n_jobs=-1)  # If cv is integer, by default is Stratifyed 
clf.fit(X_train, y_train)
print("Best Params=",clf.best_params_, "Accuracy=", clf.best_score_)

In [ ]:
## Train and Print A Decision Tree (with best params)

clf = tree.DecisionTreeClassifier(criterion='entropy', min_samples_split=clf.best_params_['min_samples_split'],min_impurity_decrease=clf.best_params_['min_impurity_decrease'])
clf = clf.fit(X_train, y_train)
pred = clf.predict(X_test)

# Obtain accuracy score of learned classifier on test data
print(clf.score(X_test, y_test))
print(sklearn.metrics.confusion_matrix(y_test, pred))
print()
print("Accuracy:", sklearn.metrics.accuracy_score(y_test, pred))
print()
print(sklearn.metrics.classification_report(y_test, pred))
epsilon = sklearn.metrics.accuracy_score(y_test, pred)
print("Interval of confidence:", proportion_confint(count=epsilon*X_test.shape[0], nobs=X_test.shape[0], alpha=0.05, method='binom_test'))

# Print tree
fig = plt.gcf()
fig.set_size_inches(800, 80)

tree.plot_tree(clf, filled=True,rounded=True)
fig.savefig('treeBestParams.png')
plt.show()

In [ ]:
# Cross-validation of the model with best params
scores = sklearn.model_selection.cross_val_score(clf, Xn, Y, cv=10)
print("Accuracy on 10 fold cross-validation:", scores)
print(np.mean(scores))